### ISSUE TITLE
Clarify supported features on the README

### ISSUE THREAD

**Issue by tssm** [freebroccolo/sml-language-server#3]
Hi!

I have been playing with the server and the language client for Neovim using `--stdio` and it seems only jump to definition is supported by the moment. Is that right or did I messed up?

**Comment by freebroccolo** [comment]
At the moment the language server doesn't implement anything beyond providing compiler errors. Not even jump to definition is supported.

I would like to add the other standard features for a language server but unfortunately it probably won't happen soon because the tooling to provide this information doesn't really exist in a usable form on the compiler side, as far as I can tell, not for MLton or SML/NJ at least.

PolyML does have some sort of IDE communications protocol that could help but I'm not sure if it's worth the effort trying to support it since none of the projects I was looking at using this for will compile with PolyML without some serious refactoring (due to build system differences).

**Comment by tssm** [comment]
Oh, weird. I can't see compiler errors but I can jump to definition probably because my tags setup.

Thanks for the answer, compiler errors is a nice feature in any case.

**Comment by freebroccolo** [comment]
The error diagnostics only show up if the project is configured in such a way that it can be compiled with sml/nj. I should document that. You can see an example of how to set it up [here](https://github.com/jonsterling/stlc-type-inference) though (take a look at the `sml.json` file).

**Comment by tssm** [comment]
Doc, yes please! I haven't see this kind of config files before. Thanks beforehand.

**Comment by tssm** [comment]
Ok, I'm developing a small library with the following structure:

```
src/main.sig
src/main.sml
main.cm
sml.json
```

The content of `main.cm` is as follow:

```
Group is
	src/main.sig
	src/main.sml
	$/basis.cm
```

The content of `sml.json`:

```json
{
	"cm": {
		"make/onSave": "main.cm"
	}
}
```

As soon as I open `src/main.sml` I notice that the Neovim's client starts the language server, but I make deliberate syntax error and I still don't see them reported. I am missing something? Maybe it's an error on the client that I'm using.

**Comment by freebroccolo** [comment]
It might be that there is some problem with how the Neovim client is launching the server.

I have never gotten one of my language servers to work with Neovim. I did make a few attempts awhile back with the OCaml language server. It seemed like it should work but one problem I faced was that in the server I used several custom messages that the client needed to be configured to respond to properly and there didn't seem to be a way to handle that well. But back then the clients were very new and just barely working. I think there were some other issues too but I don't remember the details.

It's been awhile since I looked at this but it doesn't appear that I've used any custom stuff though so that may not be a factor after all.

Are you able to get errors reported by language servers to show up for anything else? I would try the typescript or go servers since they seemed to be the most complete last time I looked.

**Comment by tssm** [comment]
I just tried with the Rust language server and it works without problem so I'm thinking again that maybe I did not set my SML project the right way

**Comment by freebroccolo** [comment]
It is possible but I'm not really surprised it isn't working as expected. I threw the server together very quickly mostly as a demo. I was hoping some other interested people might pick up and do something with it because I don't write much SML myself. I did verify that it worked with a custom version of the `vscode-sml` extension but haven't used it beyond that.

Frankly, I would not recommend spending a lot of time trying to get it to work unless you are interested in developing the server itself. I don't really consider it to be in a usable state at this point.

**Comment by tssm** [comment]
Oh, I see... Well, I'll try to play with it (I don't have experience with TypeScript) and try to debug it. Thanks for all the answers!
